config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :users do
    resources :articles, only: [:index]
  end

  resources :articles

  resource :session, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  author_id  :string
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'csv'

class Article < ActiveRecord::Base
  belongs_to :author, class_name: 'User'

  validates_presence_of :author, :title, :body

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.map do |article|
        csv << article.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  role            :integer          default(0), not null
#  session_key     :string
#  password_digest :string
#

class User < ActiveRecord::Base
  has_secure_password

  enum role: { member: 0, admin: 1, editor: 2 }

  has_many :articles, foreign_key: :author_id

  validates_presence_of :first_name, :last_name, :email, :password_digest
  validates_length_of :password_digest, within: 8..64
  validates_uniqueness_of :email

  scope :by_letter, ->(letter) {
    where('last_name LIKE ?', "#{letter}%").order(:last_name)
  }

  def correct_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def name
    [first_name, last_name].join(' ')
  end

  def random_session_key
    SecureRandom.hex(24)
  end

  def destroy_session_key!
    update_attributes(session_key: nil)
  end

  def reset_session_key!
    new_session_key = random_session_key
    while User.find_by_session_key(new_session_key)
      new_session_key = random_session_key
    end
    update_attributes(session_key: new_session_key)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    return nil unless session[:session_key].present?
    @current_user ||= User.find_by_session_key(session[:session_key])
  end

  def logged_in?
    current_user.present?
  end

  def require_user!
    redirect_to login_path unless logged_in?
  end

  def send_csv(data)
    send_data(
      data.to_csv,
      type: 'text/csv; charset=utf8; header=present',
      disposition: 'attachment; filename=articles.csv'
    )
  end

  def login_user!

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user!, only: [:create, :edit, :new, :update]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: 'Article Created'
    else
      flash.now[:error] = @article.errors.full_messages.to_sentence
      render :new, locals: { article: @article }
    end
  end

  def destroy
    article.destroy
    redirect_to articles_path, notice: 'Article Deleted'
  end

  def edit
    render :edit, locals: { article: article }
  end

  def index
    respond_to do |format|
      format.html { render :index, locals: { articles: articles } }
      format.csv { send_csv articles }
      format.json { render json: articles }
    end
  end

  def new
    @article = Article.new
    render :new, locals: { article: @article }
  end

  def show
    render :show, locals: { article: article }
  end

  def update
    if article.update_attributes(article_params)
      redirect_to article_path(article), notice: 'Article Updated'
    else
      flash.now[:error] = article.errors.full_messages.to_sentence
      render :edit, locals: { article: article }
    end
  end

  private

  def article
    @article ||= Article.find(params[:id])
  end

  def articles
    @articles ||= if params[:user_id]
      Article.where(author_id: params[:user_id])
    else
      Article.all
    end
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def authorize_user!
    return true if current_user.admin?
    unless current_user.articles.where(id: article.id).present?
      head :unauthorized
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    if user && user.correct_password?(params[:password])
      user.reset_session_key!
      session[:session_key] = user.session_key
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now[:error] = 'Invalid login'
      render :new
    end
  end

  def destroy
    user && user.destroy_session_key!
    reset_session
    redirect_to root_path
  end

  private

  def user
    @user ||= User.find_by_email(params[:email])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<%= form_for article do |f| %>
  <%= f.text_field :title %><br>
  <%= f.text_area :body %><br>
  <%= f.submit 'Update' %>
<% end %>

app/views/articles/index.html.erb
<% if logged_in? %>
  <%= link_to 'New Article',  new_article_path %>
<% end %>

<h1>Articles:</h1>
<ul>
  <% articles.map do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

<%= link_to 'JSON', articles_path(format: :json) %> |
<%= link_to 'CSV', articles_path(format: :csv) %>

app/views/articles/new.html.erb
<%= form_for article do |f| %>
  <%= f.text_field :title, placeholder: 'Title' %><br>
  <%= f.text_area :body, placeholder: 'Body' %><br>
  <%= f.submit 'Create' %>
<% end %>

app/views/articles/show.html.erb
<h1><%= article.title %></h1>

<%= simple_format(article.body) %>

<%= link_to 'Edit', edit_article_path(article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Home', root_path %> |

<% if logged_in? %>
  <%= current_user.email %> | <%= link_to 'Logout', logout_path %>
<% else %>
  <%= link_to 'Login', login_path %>
<% end %>

| <%= link_to 'About Us', '#', data: { show: '[data-about-us]' } %>
  <span data-about-us class="hide">-- We are your friends.</span>
<hr>

<%= yield %>

</body>
</html>